FROM node:16-alpine3.12

LABEL version="1.0"
LABEL description="React Frontend for the Organic Food Api"

WORKDIR /app
RUN npm config set unsafe-perm true

COPY ./package*.json ./

RUN npm install

COPY . .

CMD [ "npm", "run", "start" ]